//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class AbsentFromSchool
    {

        [JsonProperty("absentFromSchoolID")]
        public Guid? AbsentFromSchoolID { get; set; }
        [JsonProperty("studentTermRegisterID")]
        public Guid StudentTermRegisterID { get; set; }
        [JsonProperty("dayAbsent")]
        public System.DateTime DayAbsent { get; set; }
        [JsonProperty("reason")]
        public string Reason { get; set; }
        [JsonProperty("dateCreated")]
        public System.DateTime DateCreated { get; set; }

        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

        public StudentTermRegister StudentTermRegister { get; set; } 
    }
}
