//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class AbsentFromLesson
    {
        [JsonProperty("absentFromLessonID")]
        public Guid? AbsentFromLessonID { get; set; }
        [JsonProperty("studentTermRegisterID")]
        public Guid StudentTermRegisterID { get; set; }
        [JsonProperty("teacherClassSubjectID")]
        public Guid TeacherClassSubjectID { get; set; }
        [JsonProperty("date")]
        public System.DateTime Date { get; set; }
        [JsonProperty("fromTime")]
        public System.TimeSpan FromTime { get; set; }
        [JsonProperty("toTime")]
        public System.TimeSpan ToTime { get; set; }
        [JsonProperty("reason")]
        public string Reason { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

        public StudentTermRegister StudentTermRegister { get; set; } 
        public TeacherClassSubject TeacherClassSubject { get; set; } 
    }
}
