//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class ClassTeacher
    {
        [JsonProperty("classID")]
        public Guid ClassID { get; set; }
        [JsonProperty("teacherID")]
        public Guid TeacherID { get; set; }
        [JsonProperty("termID")]
        public Guid TermID { get; set; }



        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }


        public Class Class { get; set; }
        public Teacher Teacher { get; set; }
        public Term Term { get; set; }
    }
}
