//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public  class Exam
    {
        [JsonProperty("studentTermRegisterID")]
        public Guid StudentTermRegisterID { get; set; }
        [JsonProperty("teacherClassSubjectID")]
        public Guid TeacherClassSubjectID { get; set; }
        [JsonProperty("mark")]
        public byte Mark { get; set; }
        [JsonProperty("grade")]
        public string Grade { get; set; }
        [JsonProperty("comment")]
        public string Comment { get; set; }


        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

        public  StudentTermRegister StudentTermRegister { get; set; }
        public  TeacherClassSubject TeacherClassSubject { get; set; }
    }
}
