//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class Log
    {
        [JsonProperty("logID")]
        public Guid? LogID { get; set; }
        [JsonProperty("teacherID")]
        public Guid TeacherID { get; set; }
        [JsonProperty("entityType")]
        public string EntityType { get; set; }
        [JsonProperty("actionType")]
        public string ActionType { get; set; }
        [JsonProperty("actionDetails")]
        public string ActionDetails { get; set; }
        [JsonProperty("actionDate")]
        public System.DateTime ActionDate { get; set; } = DateTime.Today;


        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

        public Teacher Teacher { get; set; }
    }
}
