//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using iGrade.Domain.DateFormater;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Setting
    {
        [JsonProperty("schoolID")]
        public Guid SchoolID { get; set; }
        [JsonProperty("examMarkSubmissionClosingDate")]
        [JsonConverter(typeof(CustomDateTimeConverter))]
        public DateTime ExamMarkSubmissionClosingDate { get; set; }
        [JsonProperty("testMarkSubmissionClosingDate")]
        [JsonConverter(typeof(CustomDateTimeConverter))]
        public DateTime TestMarkSubmissionClosingDate { get; set; }
        [JsonProperty("termLastDateUpdated")]
        public DateTime TermLastDateUpdated { get; set; }
        [JsonProperty("termID")]
        public Guid TermID { get; set; }
        [JsonProperty("maximumTermPerYear")]
        public int MaximumTermPerYear { get; set; }


        [JsonProperty("teacherNoticeBoard")]
        public string TeacherNoticeBoard { get; set; }
        [JsonProperty("parentNotice")]
        public string ParentNotice { get; set; }

        [JsonProperty("absentFromSchoolSmsNotify")]
        public bool AbsentFromSchoolSmsNotify { get; set; }
        [JsonProperty("absentFromSchoolEmailNotify")]
        public bool AbsentFromSchoolEmailNotify { get; set; }


        [JsonProperty("lessonPlanNotEditedAfterDaysOfCreation")]
        public int LessonPlanNotEditedAfterDaysOfCreation { get; set; }
        [JsonProperty("lessonPlanTeacherCanSelfApprove")]
        public bool LessonPlanTeacherCanSelfApprove { get; set; }


        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

    }
}
