//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Student
    {
        [JsonProperty("studentID")]
        public Guid? StudentID { get; set; }
        [JsonProperty("schoolID")]
        public Guid SchoolID { get; set; }
        [JsonProperty("studentName")]
        public string StudentName { get; set; }
        [JsonProperty("studentMidName")]
        public string StudentMidName { get; set; }
        [JsonProperty("studentSurname")]
        public string StudentSurname { get; set; }
        [JsonProperty("regNumber")]
        public string RegNumber { get; set; }
        [JsonProperty("iDnational")]
        public string IDnational { get; set; }
        [JsonProperty("isMale")]
        public bool IsMale { get; set; }
        [JsonProperty("dOB")]
        public System.DateTime DOB { get; set; }
        [JsonProperty("email")]
        public string Email { get; set; }
        [JsonProperty("contactEmail")]
        public string ContactEmail { get; set; }
        [JsonProperty("phone")]
        public string Phone { get; set; }
        [JsonProperty("studentDateCreated")]
        public System.DateTime StudentDateCreated { get; set; }


        [JsonProperty("isDeleted")]
        public System.DateTime? IsDeleted { get; set; }
        [JsonProperty("lastModifiedBy")]
        public string LastModifiedBy { get; set; }
        [JsonProperty("isLive")]
        public bool? IsLive { get; set; }

    }
}
