//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGrade.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class TeacherDto
    {
        [JsonProperty("teacherID")]
        public Guid? TeacherID { get; set; }
        [JsonProperty("schoolID")]
        public Guid SchoolID { get; set; }
        [JsonProperty("isAdmin")]
        public bool IsAdmin { get; set; }
        [JsonProperty("teacherUsername")]
        public string TeacherUsername { get; set; }
        [JsonProperty("teacherEmail")]
        public string TeacherEmail { get; set; }
        [JsonProperty("teacherFullname")]
        public string TeacherFullname { get; set; }
        [JsonProperty("teacherPhone")]
        public string TeacherPhone { get; set; }
        [JsonProperty("isActive")]
        public bool IsActive { get; set; }
        [JsonProperty("createdDate")]
        public System.DateTime CreatedDate { get; set; }
        
    }
}
